ENT.Category	= "RocketMania's"
ENT.Type = "anim"
ENT.Base = "base_anim"
ENT.PrintName	= "Slot Machine"
ENT.Author	= "RocketMania"
ENT.Contact	= ""
ENT.Purpose	= ""
ENT.Instructions= ""
ENT.Spawnable	= true
ENT.AdminSpawnable = true
