g_DarkRPEntData = {
	["ent_volatile"] = {PrintName = "Volatile Waste", Model = "models/props/CS_militia/paintbucket01.mdl"},
	["ent_kevlar"] = {PrintName = "Kevlar", Model = "models/props_c17/SuitCase_Passenger_Physics.mdl"},
	["zig_ink"] = {PrintName = "Ink", Model = "models/props_junk/metal_paintcan001a.mdl"},
	["zig_printer_topaz"] = {PrintName = "Topaz Printer", Model = "models/props_c17/consolebox01a.mdl"},
	["zig_printer_amethyst"] = {PrintName = "Amethyst Printer", Model = "models/props_c17/consolebox01a.mdl"},
	["zig_battery"] = {PrintName = "Battery", Model = "models/Items/car_battery01.mdl"},
	["zig_printer_sapphire"] = {PrintName = "Sapphire Printer", Model = "models/props_c17/consolebox01a.mdl"},
	["zig_printer_emerald"] = {PrintName = "Emerald Printer", Model = "models/props_c17/consolebox01a.mdl"},
	["ent_bleach"] = {PrintName = "Bleach", Model = "models/props_junk/garbage_plasticbottle001a.mdl"},
	["book_torah"] = {PrintName = "Torah", Model = "models/props_lab/binderredlabel.mdl"},
	["ent_medkit"] = {PrintName = "Medical Kit", Model = "models/Items/HealthKit.mdl"},
	["book_quran"] = {PrintName = "Quran", Model = "models/props_lab/bindergreen.mdl"},
	["zig_printer_ruby"] = {PrintName = "Ruby Printer", Model = "models/props_c17/consolebox01a.mdl"},
	["zig_printer_diamond"] = {PrintName = "Diamond Printer", Model = "models/props_c17/consolebox01a.mdl"},
	["book_bible"] = {PrintName = "Bible", Model = "models/props_lab/binderblue.mdl"},
	["lite_p228"] = {PrintName = "P228", Model = "models/weapons/w_pist_p228.mdl"},
	["lite_famas"] = {PrintName = "FAMAS", Model = "models/weapons/w_rif_famas.mdl"},
	["weapon_remotemine"] = {PrintName = "Remote Mine", Model = "models/weapons/w_slam.mdl"},
	["lite_g3sg1"] = {PrintName = "G3/SG-1", Model = "models/weapons/w_snip_g3sg1.mdl"},
	["weapon_molotov"] = {PrintName = "Molotov Cocktail", Model = "models/props_junk/GlassBottle01a.mdl"},
	["weapon_rocketlauncher"] = {PrintName = "Rocket Launcher", Model = "models/weapons/w_rocket_launcher.mdl"},
	["lite_smokegrenade"] = {PrintName = "Smoke Grenade", Model = "models/weapons/w_eq_smokegrenade.mdl"},
	["lite_sg550"] = {PrintName = "SG-550", Model = "models/weapons/w_snip_sg550.mdl"},
	["lite_sg552"] = {PrintName = "SG-552", Model = "models/weapons/w_rif_sg552.mdl"},
	["lite_hegrenade"] = {PrintName = "HE Grenade", Model = "models/weapons/w_eq_fraggrenade.mdl"},
	["lite_scout"] = {PrintName = "Scout", Model = "models/weapons/w_snip_scout.mdl"},
	["lite_m249"] = {PrintName = "M249", Model = "models/weapons/w_mach_m249para.mdl"},
	["lite_mac10"] = {PrintName = "MAC10", Model = "models/weapons/w_smg_mac10.mdl"},
	["weapon_stickylauncher"] = {PrintName = "Stickybomb Launcher", Model = "models/weapons/w_shotgun.mdl"},
	["keypad_cracker"] = {PrintName = "Keypad Cracker", Model = "models/weapons/w_c4.mdl"},
	["weapon_jihad"] = {PrintName = "Jihad Bomb", Model = "models/weapons/w_c4.mdl"},
	["med_kit"] = {PrintName = "Medic Kit", Model = "models/weapons/w_medkit.mdl"},
	["unarrest_stick"] = {PrintName = "Unarrest Baton", Model = "models/weapons/w_stunbaton.mdl"},
	["lite_galil"] = {PrintName = "Galil", Model = "models/weapons/w_rif_galil.mdl"},
	["lite_m3"] = {PrintName = "M3 Super 90", Model = "models/weapons/w_shot_m3super90.mdl"},
	["lite_mp5"] = {PrintName = "MP5", Model = "models/weapons/w_smg_mp5.mdl"},
	["weapon_grenadelauncher"] = {PrintName = "Grenade Launcher", Model = "models/weapons/w_shotgun.mdl"},
	["lite_ak47"] = {PrintName = "AK-47", Model = "models/weapons/w_rif_ak47.mdl"},
	["lite_dualberettas"] = {PrintName = "Dual 96G Elite Berettas", Model = "models/weapons/w_pist_elite.mdl"},
	["lite_deagle"] = {PrintName = "Desert Eagle", Model = "models/weapons/w_pist_deagle.mdl"},
	["lite_ump"] = {PrintName = "UMP", Model = "models/weapons/w_smg_ump45.mdl"},
	["lite_glock"] = {PrintName = "Glock 18", Model = "models/weapons/w_pist_glock18.mdl"},
	["lite_awp"] = {PrintName = "AWP", Model = "models/weapons/w_snip_awp.mdl"},
	["lite_p90"] = {PrintName = "P90", Model = "models/weapons/w_smg_p90.mdl"},
	["weapon_zipties"] = {PrintName = "Zipties", Model = "models/Items/CrossbowRounds.mdl"},
	["lockpick"] = {PrintName = "Lockpick", Model = "models/weapons/w_crowbar.mdl"},
	["lite_xm1014"] = {PrintName = "XM1014", Model = "models/weapons/w_shot_xm1014.mdl"},
	["lite_fiveseven"] = {PrintName = "FN Five-seveN", Model = "models/weapons/w_pist_fiveseven.mdl"},
	["lite_aug"] = {PrintName = "AUG", Model = "models/weapons/w_rif_aug.mdl"},
	["lite_tmp"] = {PrintName = "TMP", Model = "models/weapons/w_smg_tmp.mdl"},
	["lite_flashbang"] = {PrintName = "Flashbang Grenade", Model = "models/weapons/w_eq_flashbang.mdl"},
	["lite_m4a1"] = {PrintName = "M4A1", Model = "models/weapons/w_rif_m4a1.mdl"},
	["weapon_c4"] = {PrintName = "C4", Model = "models/weapons/w_c4.mdl"},
	["ent_beer"] = {PrintName = "Beer", Model = "models/props_junk/garbage_glassbottle003a.mdl"},
	["ent_painkillers"] = {PrintName = "Painkillers", Model = "models/props_junk/garbage_metalcan002a.mdl"},
	["ent_water"] = {PrintName = "Water", Model = "models/props/cs_office/Water_bottle.mdl"},
	["ent_steroids"] = {PrintName = "Steroids", Model = "models/Items/battery.mdl"},
	["ent_stdmeds"] = {PrintName = "STD Medication", Model = "models/props_lab/jar01a.mdl"},
	["weapon_bbgun"] = {PrintName = "Red Ryder BB Gun", Model = "models/weapons/w_snip_scout.mdl"},
	["weapon_tranq"] = {PrintName = "Tranquilizer Gun", Model = "models/weapons/w_snip_scout.mdl"},
	["ent_stove"] = {PrintName = "Stove", Model = "models/props_c17/furnitureStove001a.mdl"},
	["ent_vodka"] = {PrintName = "Vodka", Model = "models/props_junk/garbage_glassbottle002a.mdl"},
	["ent_ied"] = {PrintName = "IED", Model = "models/props_junk/metalgascan.mdl"},
	["ent_banana"] = {PrintName = "Banana", Model = "models/props/cs_italy/bananna.mdl"},
	["ent_gas"] = {PrintName = "Gas", Model = "models/props_junk/propane_tank001a.mdl"},
	["ent_potato"] = {PrintName = "Potato", Model = "models/props_phx/misc/potato.mdl"},
	["ent_keg"] = {PrintName = "Keg", Model = "models/props_c17/woodbarrel001.mdl"},
	["ent_oilminerpro"] = {PrintName = "Professional Oil Miner", Model = "models/props_industrial/winch_deck.mdl"},
	["ent_barrel"] = {PrintName = "Barrel", Model = "models/props_borealis/bluebarrel001.mdl"},
	["ent_orange"] = {PrintName = "Orange", Model = "models/props/cs_italy/orange.mdl"},
	["ent_injection"] = {PrintName = "Injection", Model = "models/props_c17/TrapPropeller_Lever.mdl"},
	["ent_pruno"] = {PrintName = "Pruno", Model = "models/props_junk/garbage_glassbottle001a.mdl"},
	["ent_oilrefinery"] = {PrintName = "Oil Refinery", Model = "models/props_c17/FurnitureFireplace001a.mdl"},
	["ent_moonshine"] = {PrintName = "Moonshine", Model = "models/props_junk/glassjug01.mdl"},
	["ent_chloride"] = {PrintName = "Chloride", Model = "models/props_junk/garbage_plasticbottle001a.mdl"},
	["ent_oilminer"] = {PrintName = "Oil Miner", Model = "models/props_industrial/winch_stern.mdl"},
	["ent_rum"] = {PrintName = "Rum", Model = "models/props/CS_militia/bottle01.mdl"},
	["ent_coca"] = {PrintName = "Coca Plant", Model = "models/props/cs_office/plant01.mdl"},
	["ent_milk"] = {PrintName = "Milk", Model = "models/props_junk/garbage_milkcarton001a.mdl"},
	["ent_pot"] = {PrintName = "Pot", Model = "models/props_c17/metalPot001a.mdl"},
	["ent_melon"] = {PrintName = "Melon", Model = "models/props_junk/watermelon01.mdl"},
	["ent_caustic"] = {PrintName = "Caustic Soda", Model = "models/props_junk/garbage_milkcarton002a.mdl"},
	["ent_fertilizer"] = {PrintName = "Fertilizer", Model = "models/props_junk/garbage_bag001a.mdl"},
	["ent_sodium"] = {PrintName = "Sodium", Model = "models/props_junk/garbage_plasticbottle002a.mdl"},
	["ent_stabilizer"] = {PrintName = "Stabilization Pills", Model = "models/props_lab/jar01b.mdl"},
	["weapon_knife"] = {PrintName = "Knife", Model = "models/weapons/w_knife_t.mdl"},
	["ent_weedplant"] = {PrintName = "Weed Plant", Model = "models/props/de_inferno/flower_barrel_static.mdl"},
	["bitminer_normal"] = {PrintName = "Bitminer", Model = "models/props_c17/consolebox01a.mdl"},
	["ent_weaponbench"] = {PrintName = "Crafting Bench", Model = "models/props_combine/breendesk.mdl"},
	["bitminer_mini"] = {PrintName = "Bitminer Mini", Model = "models/props_c17/consolebox01a.mdl"},
	["ent_illegalgunparts"] = {PrintName = "Illegal Gun Parts", Model = "models/weapons/w_pist_elite_dropped.mdl"},
	["ent_scrap"] = {PrintName = "Scrap Metal", Model = "models/props_vehicles/carparts_door01a.mdl"},
	["ent_spring"] = {PrintName = "Spring", Model = "models/props_c17/TrapPropeller_Lever.mdl"},
	["ent_radio"] = {PrintName = "Radio", Model = "models/props/cs_office/radio.mdl"},
	["weapon_xbow"] = {PrintName = "Crossbow", Model = "models/weapons/w_crossbow.mdl"},
	["weapon_tennis"] = {PrintName = "Tennis Racket", Model = "models/weapons/w_crowbar.mdl"},
	["weapon_boltcutters"] = {PrintName = "Bolt Cutters", Model = ""},
	["weapon_pipeshotgun"] = {PrintName = "Pipe Shotgun", Model = "models/props_canal/mattpipe.mdl"},
	["weapon_monkeymilk"] = {PrintName = "Monkey Milk", Model = "models/props_junk/garbage_milkcarton002a.mdl"},
	["weapon_flamethrower"] = {PrintName = "Flamethrower", Model = "models/weapons/w_shotgun.mdl"},
	["weapon_guitar"] = {PrintName = "Guitar", Model = "models/props_phx/misc/fender.mdl"},
}
