g_DarkRPEntData = {
	["swb_glock18"] = {PrintName = "Glock 18", Model = "models/weapons/3_pist_glock18.mdl"},
	["swb_357"] = {PrintName = ".357 Revolver", Model = "models/weapons/w_357.mdl"},
	["swb_deagle"] = {PrintName = "Desert Eagle .50 AE", Model = "models/weapons/3_pist_deagle.mdl"},
	["swb_fiveseven"] = {PrintName = "FN Five-seveN", Model = "models/weapons/3_pist_fiveseven.mdl"},
	["swb_p228"] = {PrintName = "P228", Model = "models/weapons/3_pist_p228.mdl"},
	["swb_m3super90"] = {PrintName = "M3 Super 90", Model = "models/weapons/3_shot_m3super90.mdl"},
	["swb_xm1014"] = {PrintName = "XM1014", Model = "models/weapons/3_shot_xm1014.mdl"},
	["swb_tmp"] = {PrintName = "Steyr TMP", Model = "models/weapons/3_smg_tmp.mdl"},
	["swb_mp5"] = {PrintName = "HK MP5", Model = "models/weapons/3_smg_mp5.mdl"},
	["swb_ump"] = {PrintName = "HK UMP .45", Model = "models/weapons/3_smg_ump45.mdl"},
	["swb_mac10"] = {PrintName = "MAC-10", Model = "models/weapons/3_smg_mac10.mdl"},
	["swb_p90"] = {PrintName = "FN P90", Model = "models/weapons/3_smg_p90.mdl"},
	["swb_ak47"] = {PrintName = "AK-47", Model = "models/weapons/3_rif_ak47.mdl"},
	["swb_m4a1"] = {PrintName = "M4A1", Model = "models/weapons/3_rif_m4a1.mdl"},
	["swb_galil"] = {PrintName = "IMI Galil ARM", Model = "models/weapons/3_rif_galil.mdl"},
	["swb_famas"] = {PrintName = "FAMAS", Model = "models/weapons/3_rif_famas.mdl"},
	["swb_sg552"] = {PrintName = "SIG SG552", Model = "models/weapons/3_rif_sg552.mdl"},
	["swb_aug"] = {PrintName = "Steyr AUG", Model = "models/weapons/3_rif_aug.mdl"},
	["swb_scout"] = {PrintName = "Steyr Scout", Model = "models/weapons/3_snip_scout.mdl"},
	["swb_awp"] = {PrintName = "AWP", Model = "models/weapons/3_snip_awp.mdl"},
	["swb_g3sg1"] = {PrintName = "G3SG1", Model = "models/weapons/3_snip_g3sg1.mdl"},
	["swb_sg550"] = {PrintName = "SIG SG550", Model = "models/weapons/3_snip_sg550.mdl"},
	["swb_m249"] = {PrintName = "M249 Para", Model = "models/weapons/3_mach_m249para.mdl"},
	["lockpick"] = {PrintName = "Lock Pick", Model = "models/weapons/w_crowbar.mdl"},
	["keypad_cracker"] = {PrintName = "Keypad Cracker", Model = "models/weapons/w_c4.mdl"},
	["med_kit"] = {PrintName = "Medic Kit", Model = "models/weapons/w_medkit.mdl"},
	["unarrest_stick"] = {PrintName = "Unarrest Baton", Model = "models/weapons/w_stunbaton.mdl"},
	["weapon_c4"] = {PrintName = "C4", Model = "models/weapons/w_c4.mdl"},
	["weapon_vape"] = {PrintName = "Vape", Model = "models/swamponions/vape.mdl"},
	["weapon_vape_juicy"] = {PrintName = "Juicy Vape", Model = "models/swamponions/vape.mdl"},
	["weapon_vape_american"] = {PrintName = "American Vape", Model = "models/swamponions/vape.mdl"},
	["weapon_vape_medicinal"] = {PrintName = "Medicinal Vape", Model = "models/swamponions/vape.mdl"},
	["weapon_vape_mega"] = {PrintName = "Mega Vape", Model = "models/swamponions/vape.mdl"},
	["weapon_bbgun"] = {PrintName = "Red Ryder BB Gun", Model = "models/weapons/w_snip_scout.mdl"},
	["durgz_aspirin"] = {PrintName = "Aspirin", Model = "models/jaanus/aspbtl.mdl"},
	["ent_medkit"] = {PrintName = "Medical Kit", Model = "models/Items/HealthKit.mdl"},
	["durgz_alcohol"] = {PrintName = "Alcohol", Model = "models/drug_mod/alcohol_can.mdl"},
	["durgz_water"] = {PrintName = "Water", Model = "models/drug_mod/the_bottle_of_water.mdl"},
	["durgz_weed"] = {PrintName = "Marijuana", Model = "models/katharsmodels/contraband/zak_wiet/zak_wiet.mdl"},
	["durgz_mushroom"] = {PrintName = "Mushroom", Model = "models/ipha/mushroom_small.mdl"},
	["durgz_meth"] = {PrintName = "Methamphetamine", Model = "models/katharsmodels/contraband/metasync/blue_sky.mdl"},
	["durgz_lsd"] = {PrintName = "LSD", Model = "models/smile/smile.mdl"},
	["durgz_pcp"] = {PrintName = "PCP", Model = "models/marioragdoll/Super Mario Galaxy/star/star.mdl"},
	["durgz_heroine"] = {PrintName = "Heroin", Model = "models/katharsmodels/syringe_out/syringe_out.mdl"},
	["durgz_cocaine"] = {PrintName = "Cocaine", Model = "models/cocn.mdl"},
	["zig_printer_topaz"] = {PrintName = "Topaz Printer", Model = "models/props_c17/consolebox01a.mdl"},
	["zig_printer_amethyst"] = {PrintName = "Amethyst Printer", Model = "models/props_c17/consolebox01a.mdl"},
	["zig_printer_emerald"] = {PrintName = "Emerald Printer", Model = "models/props_c17/consolebox01a.mdl"},
	["zig_printer_ruby"] = {PrintName = "Ruby Printer", Model = "models/props_c17/consolebox01a.mdl"},
	["zig_printer_sapphire"] = {PrintName = "Sapphire Printer", Model = "models/props_c17/consolebox01a.mdl"},
	["zig_printer_diamond"] = {PrintName = "Diamond Printer", Model = "models/props_c17/consolebox01a.mdl"},
	["zig_battery"] = {PrintName = "Battery", Model = "models/Items/car_battery01.mdl"},
	["zig_ink"] = {PrintName = "Ink", Model = "models/props_junk/metal_paintcan001a.mdl"},
	["ent_bleach"] = {PrintName = "Bleach", Model = "models/props_junk/garbage_plasticbottle001a.mdl"},
	["ent_kevlar"] = {PrintName = "Kevlar", Model = "models/props_c17/SuitCase_Passenger_Physics.mdl"}
}
